import { Outfit } from "next/font/google";
import "./globals.css";
import Navigation from "../components/Navbar/Navigation";
import MouseTrail from "../components/MouseTrail";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "CDDA",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${outfit.className}`}>
        <Navigation />
        <MouseTrail />
        <div className=" mt-[80px] md:mt-28">{children}</div>
      </body>
    </html>
  );
}
